### PR TITLE
Support ghc 9.12

### PR DESCRIPTION
**Pull request by erikd**

### CODE REVIEW

**Comment by dmwit** [comment]
Merged it, but the CI failed, so I reverted it. (I wonder if github warned me that would happen before I hit merge? I didn't see anything obvious.) Now this merge request is in a sort of weird state where it says I merged it but the repo doesn't have your changes. Sorry.

Wanna re-open the request?

**Comment by erikd** [comment]
Will do.

**Comment by erikd** [comment]
Previous failure may have been due to using a pre-release version of `ghc-9.12.` Should be rectified in https://github.com/dmwit/universe/pull/72 .

**Comment by phadej** [comment]
I'm sorry, but this is not helpful. I have been maintaining `universe` for many years now, and this screws up my workflow. The repository is now in a messy state, and someone needs to clean up it. I'm not happy, as it probably be me.

**Comment by phadej** [comment]
To say it very clearly: this half baked PR while have good intentions causes me more work.

**Comment by erikd** [comment]
> I'm sorry, but this is not helpful. I have been maintaining `universe` for many years now, and this screws up my workflow. The repository is now in a messy state, and someone needs to clean up it. I'm not happy, as it probably be me.

For repos where know are are the maintainer I raise issues rather than PRs. You are not listed as the maintainer on the Hackage page for `universe-base`.

**Comment by phadej** [comment]
Ain't I?

image

**Comment by erikd** [comment]
You are not listed here:
universe

**Comment by phadej** [comment]
That's fair, but `maintainer` field is weird one; it's a field per version and while may be useful as such, it's really easily stale information. Looks like we didn't kept it up to date in `scintific`, or `aeson`, or I wonder how many other packages.

I think I'll change it to something generic, like "check who made the release and/or GitHub".

**Comment by dmwit** [comment]
It's not Erik's fault the repo is in a weird state, it's mine. I'm sorry I did that, and also I'm a little surprised; what state is left odd once I dropped the merge?

In any case, this was my mistake.

**Pull request merged**
